### ISSUE TITLE
add program in python and java for implementing tower of hanoi

### ISSUE THREAD

**Issue by tornado-12** [tornado-12/learn-to-code#10]
add program for implementing Tower of Hanoi in java and python. add programs for python and java in there particular folder

**Comment by vedanttttt** [comment]
Assign it to me , I can solve it.

**Comment by shikhar-sharma1703** [comment]
I would like to perform this task. Could you please assign it to me?

**Comment by tornado-12** [comment]
@vedanttttt yes you can take up this issue

**Comment by tornado-12** [comment]
please add your file by name of tower-of-hanoi

**Comment by vedanttttt** [comment]
> please add your file by name of tower-of-hanoi

Okay
