### ISSUE TITLE
Add basic programs of Pearl

### ISSUE THREAD

**Issue by tornado-12** [tornado-12/learn-to-code#27]
Create a new folder named Pearl and add all the basics programs into it

**Comment by captainaadesh** [comment]
Assign it to me! I can do this

**Comment by tornado-12** [comment]
Okay @captainaadesh

**Comment by captainaadesh** [comment]
@tornado-12 Hey I have added it please check and merge my PR. Thank you!

**Comment by tornado-12** [comment]
thanks @captainaadesh

**Comment by captainaadesh** [comment]
@tornado-12 My pleasure
