### ISSUE TITLE
Add programs in java for quick and merge sort

### ISSUE THREAD

**Issue by tornado-12** [tornado-12/learn-to-code#29]
Add your files in Java folder

**Comment by Amitsharma45** [comment]
@tornado-12  please assign this issue to me.

**Comment by Jaideep07** [comment]
I would like to work on this

**Comment by saiharsha-22** [comment]
@tornado-12 Hi can you please assign this work to me. I will solve the work.

**Comment by nits01** [comment]
Hi would like to take this.
