### ISSUE TITLE
add programs in python for searching and sorting 

### ISSUE THREAD

**Issue by tornado-12** [tornado-12/learn-to-code#4]
fork this repo and create a new folder named python and add programs for seraching and sorting

**Comment by theshikharmalik** [comment]
Hello @tornado-12, I would like to contribute in python, would u please assign this to me ?

**Comment by KushGrandhi** [comment]
hi @tornado-12 , I would like to do this task

**Comment by Deeksha-Rawat** [comment]
Hi! @tornado-12 , I would like to do this for you , could you please assign it to me. 😊

**Comment by tornado-12** [comment]
@shikharmaxx i will assign you this issue

**Comment by tornado-12** [comment]
@shikharmaxx  you have to just add .py files for programs of linear and binary search and selection ,insertion and bubble sort

**Comment by tornado-12** [comment]
@Deeksha-Rawat @KushGrandhi you can check up the other issues
i will add more issues

**Comment by theshikharmalik** [comment]
> @shikharmaxx you have to just add .py files for programs of linear and binary search and selection ,insertion and bubble sort

@tornado-12 Should I make a new folder for py programs and then add these files to it ?

**Comment by tornado-12** [comment]
yes create a folder by name of python and add all the python files in it

**Comment by tornado-12** [comment]
@Deeksha-Rawat , @KushGrandhi you can check  out new issues

**Comment by Yash1256** [comment]
Sir I have Forked the Repo and started contributing and Making Files But when I came I here saw so many People are asking for assigning so U can also check the history of fork even too. @tornado-12 Sir Please Consider the Request.

**Comment by tornado-12** [comment]
@Yash1256 okay i will merge your request as there has been no response from @shikharmaxx

**Comment by tornado-12** [comment]
thanks @Yash1256 for your contribution
