### ISSUE TITLE
program for binary search tree in cpp

### ISSUE THREAD

**Issue by Mayank-100** [tornado-12/learn-to-code#44]
hello @tornado-12  I can  add program to implement binary search tree in cpp for this repository.

**Comment by tornado-12** [comment]
Okay @Mayank-100 please add you files in folder c++/ data structures

**Comment by NASEEB-06** [comment]
can i take this issue??

**Comment by dag2104** [comment]
If the issue is still open can I complete it ?

**Comment by parvsharmaa** [comment]
hey, Can i work on this issue ?

**Comment by tornado-12** [comment]
@dag2104 you can start working on this issue

**Comment by dag2104** [comment]
I will start working straight away
