### ISSUE TITLE
add JavaScript programs for searching and sorting 

### ISSUE THREAD

**Issue by tornado-12** [tornado-12/learn-to-code#9]
create a new folder by name of javascript and add your files there

**Comment by FinalGetsugaa** [comment]
I want to do it.Please assign the task.

**Comment by tornado-12** [comment]
@FinalGetsugaa ok you can check this issue

**Comment by tornado-12** [comment]
please create a new folder by name of javascript and add files in it

**Comment by FinalGetsugaa** [comment]
Sure

**Comment by tornado-12** [comment]
@FinalGetsugaa please add programs for selection and insertion sort
