### ISSUE TITLE
Heap sort in Java

### ISSUE THREAD

**Issue by ShivamChoudhary17** [tornado-12/learn-to-code#95]
Hi!
I would like to add  **Heap Sort**
Could you please assign this issue to me?
Thank You!

**Comment by tornado-12** [comment]
@ShivamChoudhary17 you can take up this issue.

**Comment by ShivamChoudhary17** [comment]
Done #103

**Comment by ShivamChoudhary17** [comment]
@tornado-12 

Done #103.
Thanks!

**Comment by tornado-12** [comment]
@ShivamChoudhary17 thanks for contributing
